os:
  - linux
#  - osx  # Right now we know it fails the socket test
language: perl6
perl6:
  - 2018.11
  - latest
allow_failures:
  - perl6: latest
install:
  - rakudobrew build zef
  - zef install --deps-only --/test .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
